
package tuten;

import java.util.*;
import javax.swing.DefaultListModel;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author yusuf
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    
    private ArrayList<Exam> e = new ArrayList<Exam>();
    private ArrayList<Diary> d = new ArrayList<Diary>();
    private ArrayList<Score> s = new ArrayList<Score>();
    private DefaultListModel<String> listModelE = new DefaultListModel<String>();
    private DefaultListModel<String> listModelD = new DefaultListModel<String>();
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    
    public AdminPage() { 
        e = Files.readArrayListFromFile("exams.ser");
        d = Files.readArrayListFromFile("diaries.ser");
        
        
        for(Exam ex: e){
            listModelE.addElement(ex.getExamName() + " - " + ex.getN() + " questions");
        }
        
        for(Diary di: d){
            String formattedStr = di.getWhenStarted().format(formatter);
            listModelD.addElement(di.getExam().getExamName() + " - " + di.getWhoSolved() + " - " + formattedStr);
        }
        
        initComponents();
        
        listExams.setModel(listModelE);
        listDiaries.setModel(listModelD);
        lblWarn.setText("Please don't enter spaces!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtN = new javax.swing.JTextField();
        lblN = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        lblB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDiaries = new javax.swing.JList<>();
        btnChoose = new javax.swing.JButton();
        lblGreet = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        lblDiaries = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listExams = new javax.swing.JList<>();
        lblExams = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblWarn = new javax.swing.JLabel();
        btnChooseExam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnAdd.setText("Add Exam");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        lblN.setText("N: ");

        lblA.setText("a:");

        lblB.setText("b:");

        listDiaries.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listDiaries);

        btnChoose.setText("Choose");
        btnChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseMouseClicked(evt);
            }
        });

        lblGreet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGreet.setText("Admin Page");

        lblDiaries.setText("Diaries:");

        lblName.setText("Name:");

        listExams.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listExams);

        lblExams.setText("Exams:");

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnChooseExam.setText("Choose");
        btnChooseExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseExamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGreet)
                .addGap(303, 303, 303)
                .addComponent(btnExit)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblName)
                                        .addComponent(lblN))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnChoose)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDiaries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnChooseExam)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblExams)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(lblGreet))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaries)
                            .addComponent(lblExams)))
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblN)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblA)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblB)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblWarn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoose)
                    .addComponent(btnDelete)
                    .addComponent(btnChooseExam))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        e = Files.readArrayListFromFile("exams.ser");

        if(!txtN.getText().equals("") &&  !txtName.getText().equals("") && !txtA.getText().equals("") && !txtB.getText().equals("")){
                
            boolean flag = true;
            boolean flag2 = true;
            int N = Integer.parseInt(txtN.getText());
            int a = Integer.parseInt(txtA.getText());
            int b = Integer.parseInt(txtB.getText());
            
            if(a > b){
                flag = false;
                lblWarn.setText("'a' can not be greater than 'b'!");
            }
            
            //need to differ exam names otherwise program crashes
            for(Exam ex: e){
                if(ex.getExamName().equals(txtName.getText())){
                    flag2 = false;
                    lblWarn.setText("Exam name already exists!");
                }
            }         

            if(flag && flag2){
                e.add(new Exam(txtName.getText(),N,a,b));
                listModelE.addElement(txtName.getText() + " - " + txtN.getText() + " questions");
        
                Files.writeArrayListToFile(e, "exams.ser");
        
                txtName.setText("");
                txtN.setText("");
                txtA.setText("");
                txtB.setText("");
                lblWarn.setText("");
            }  
        }
        
        

    
       
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        
        Object selectedValue = listExams.getSelectedValue();
        
        if(selectedValue != null){
            e = Files.readArrayListFromFile("exams.ser");
            String splitted = listExams.getSelectedValue().split(" ")[0];
 
            Iterator<Exam> iterator = e.iterator();
            int i = 0,j = 0;
            while (iterator.hasNext()) {
                Exam ex = iterator.next();
                if (splitted.equals(ex.getExamName())) {
                    iterator.remove(); 
                    j = i;
                }
                i++;
            }
            listModelE.remove(j);
            Files.writeArrayListToFile(e, "exams.ser");
        }
        
       
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseMouseClicked
        Object selectedValue = listDiaries.getSelectedValue();
        
        if(selectedValue != null){
            d = Files.readArrayListFromFile("diaries.ser");
            String date = listDiaries.getSelectedValue().split(" ")[4];
            String time = listDiaries.getSelectedValue().split(" ")[5];
            
            for(Diary di: d){ // we differ each diary via their date and time here
                if(di.getWhenStarted().format(formatter).split(" ")[0].equals(date) && di.getWhenStarted().format(formatter).split(" ")[1].equals(time)){
                    DiaryPage dp = new DiaryPage(di.getExam(),di.getWhoSolved(),di.getWhenStarted().format(formatter));
                    dp.setVisible(true);
                    
                }
            }
            
        }
    }//GEN-LAST:event_btnChooseMouseClicked

    private void btnChooseExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseExamMouseClicked
         Object selectedValue = listExams.getSelectedValue();
        
        if(selectedValue != null){
            e = Files.readArrayListFromFile("exams.ser");
            String examName = listExams.getSelectedValue().split(" ")[0];
            
            for(Exam ex: e){
                if(ex.getExamName().equals(examName)){
                    ScorePage sp = new ScorePage(ex.getScores());
                    sp.setVisible(true);
                }
            }
            
        }
        
    }//GEN-LAST:event_btnChooseExamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnChooseExam;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblDiaries;
    private javax.swing.JLabel lblExams;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWarn;
    private javax.swing.JList<String> listDiaries;
    private javax.swing.JList<String> listExams;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
