
package tuten;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.swing.Timer;

/**
 *
 * @author yusuf
 */
public class ExamPage extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ExamPage
     */
    
    private ArrayList<Exam> e = new ArrayList<Exam>();
    private ArrayList<Diary> d = new ArrayList<Diary>();
    private final Exam exam;
    private int counter = 0;
    private final LocalDateTime whenStarted;
    private final String whoSolved;
    private int trueCounter = 0;
    private int falseCounter = 0;
    private Timer timer;
    private int qTimeSolved = 0;
    private int parsed;
    
    public ExamPage(Exam exam, String whoLogged) {
        this.exam = exam;
        this.whenStarted = LocalDateTime.now();
        this.whoSolved = whoLogged;
        String contain = "This exam contains ";
        initComponents();
        
        lblNum1.setText(Integer.toString(exam.getQuestions().get(this.counter).getNum1()));
        lblNum2.setText(Integer.toString(exam.getQuestions().get(this.counter).getNum2()));
        contain = contain + exam.getN() +" questions.";
        lblContain.setText(contain);
        this.timer = new Timer(1000,this);
        start();
    }
    
    
    public void actionPerformed(ActionEvent e){
        try{
            Integer j = Integer.valueOf(this.lblTimer.getText());
            this.qTimeSolved++;
            j++;
            this.lblTimer.setText(Integer.toString(j));
        }catch(NumberFormatException ex){
            ex.printStackTrace();
        }
    }
    
    public void start(){
        this.timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnswer = new javax.swing.JTextField();
        lblNum1 = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblQuest = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        lblTrue = new javax.swing.JLabel();
        lblTF = new javax.swing.JLabel();
        lblContain = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNum1.setText("1");

        lblX.setText("x");

        lblNum2.setText("2");

        lblE.setText("=");

        lblQuest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuest.setText("Question 1");

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });

        lblContain.setText("jLabel1");

        lblTimer.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContain, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblX)
                                .addGap(12, 12, 12)
                                .addComponent(lblNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblE)
                                .addGap(12, 12, 12)
                                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblContain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuest)
                        .addGap(18, 18, 18)
                        .addComponent(lblTrue, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNum1)
                            .addComponent(lblX)
                            .addComponent(lblNum2)
                            .addComponent(lblE)
                            .addComponent(btnOK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lblTF))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTimer)))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        
        int answer;
        int qNumber;
        int qTime = qTimeSolved; // we need to make zero qTimeSolved after answer
        this.qTimeSolved = 0;
        
        if(!txtAnswer.getText().equals("")){
            if(this.counter < this.exam.getN()-1){
                String strT = "T = ";
                String strF = " F = ";
                
                answer = Integer.parseInt(txtAnswer.getText());
                this.exam.getQuestions().get(this.counter).setAnswer(answer);
                
                if(answer == this.exam.getQuestions().get(this.counter).getResult()){
                    this.exam.getQuestions().get(this.counter).setTrue(true);
                    lblTrue.setText("True!");
                    this.trueCounter ++;
                    strT += this.trueCounter;
                    strF += this.falseCounter;
                    lblTF.setText(strT + strF);
                }else{
                    lblTrue.setText("False!");
                    this.falseCounter += 1;
                    strT += this.trueCounter;
                    strF += this.falseCounter;
                    lblTF.setText(strT + strF);
                }
                
                exam.getQuestions().get(this.counter).setTimePassed(qTime);
                txtAnswer.setText("");
                this.counter++;
                lblNum1.setText(Integer.toString(this.exam.getQuestions().get(this.counter).getNum1()));
                lblNum2.setText(Integer.toString(this.exam.getQuestions().get(this.counter).getNum2())); 
                qNumber = counter + 1;
                lblQuest.setText("Question " + qNumber);
            }
            else if(this.counter == this.exam.getN()-1){
                String strT = "T = ";
                String strF = " F = ";

                answer = Integer.parseInt(txtAnswer.getText());
                this.exam.getQuestions().get(this.counter).setAnswer(answer);
                
                if(answer == exam.getQuestions().get(this.counter).getResult()){
                    this.exam.getQuestions().get(this.counter).setTrue(true);
                    lblTrue.setText("True!");
                    this.trueCounter ++;
                    strT += this.trueCounter;
                    strF += this.falseCounter;
                    lblTF.setText(strT + strF);
                }else{
                    lblTrue.setText("False!");
                    this.falseCounter += 1;
                    strT += this.trueCounter;
                    strF += this.falseCounter;
                    lblTF.setText(strT + strF);
                }
                
                e = Files.readArrayListFromFile("exams.ser");          
                for(Exam ex: e){
                    if(ex.getExamName().equals(this.exam.getExamName())){
                        this.parsed = Integer.valueOf(lblTimer.getText());
                        ex.getScores().add(new Score(this.whoSolved,this.trueCounter,parsed));
                    }
                }
                
                exam.getQuestions().get(this.counter).setTimePassed(qTime);
                txtAnswer.setText("");
                d = Files.readArrayListFromFile("diaries.ser");
                d.add(new Diary(this.whoSolved,exam,this.whenStarted,new Score(this.whoSolved,this.trueCounter,parsed)));
                
                Files.toExcel(new Diary(this.whoSolved,exam,this.whenStarted,new Score(this.whoSolved,this.trueCounter,parsed)));
                Files.writeArrayListToFile(d, "diaries.ser");
                Files.writeArrayListToFile(e, "exams.ser");
                this.counter++;
            }
        }
        else if(this.counter == this.exam.getN()){
            this.dispose();
        }   
    }//GEN-LAST:event_btnOKMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblContain;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblQuest;
    private javax.swing.JLabel lblTF;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTrue;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
