
package tuten;

import java.util.ArrayList;

/**
 *
 * @author yusuf
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Giris
     */
    
    private String whoLogged;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblUName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLog = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        btnSign = new javax.swing.JButton();
        radParent = new javax.swing.JRadioButton();
        radChild = new javax.swing.JRadioButton();
        signSucc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUName.setText("Username:");

        lblPassword.setText("Password:");

        btnLog.setText("Log in");
        btnLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogMouseClicked(evt);
            }
        });

        welcome.setText("Welcome Dear User!");

        btnSign.setText("Signup");
        btnSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignMouseClicked(evt);
            }
        });

        buttonGroup1.add(radParent);
        radParent.setText("Parent");

        buttonGroup1.add(radChild);
        radChild.setText("Child");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Multiplication Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radParent)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(radChild)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblUName)
                                        .addComponent(lblPassword))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtUName)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSign)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnLog)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(signSucc, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(welcome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUName)
                    .addComponent(txtUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radParent)
                    .addComponent(radChild))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSign)
                    .addComponent(btnLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signSucc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogMouseClicked
        ArrayList<Parent> p = new ArrayList<Parent>();
        ArrayList<Child> c = new ArrayList<Child>();
        p = Files.readArrayListFromFile("parents.ser");
        c = Files.readArrayListFromFile("children.ser");
        boolean flag2 = false;
        
        if(radParent.isSelected()){
            for(Parent pr: p){
                if(txtUName.getText().equals(pr.getUsername()) && txtPassword.getText().equals(pr.getPassword())){
                    flag2 = true;
                    this.whoLogged = txtUName.getText();
                    
                }
            }
            
            if(flag2){
                AdminPage ap = new AdminPage();
                ap.setVisible(true);
                this.dispose();
                
            }else{
                signSucc.setText("Couldn't log in!");
            }
            
        }
        
       if(radChild.isSelected()){
            for (Child child : c) {
                if(txtUName.getText().equals(child.getUsername()) && txtPassword.getText().equals(child.getPassword())){
                    flag2 = true;
                    this.whoLogged = txtUName.getText();
                }
            }
            
            if(flag2){
                ChildPage cp = new ChildPage(whoLogged);
                cp.setVisible(true);
                this.dispose();
            }else{
                signSucc.setText("Couldn't log in!");
            }  
       }
        
        if(!radParent.isSelected() && !radChild.isSelected()){
            signSucc.setText("Please choose Child or Parent!");
        }  
    }//GEN-LAST:event_btnLogMouseClicked

    private void btnSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignMouseClicked
        ArrayList<Parent> p = new ArrayList<Parent>();
        ArrayList<Child> c = new ArrayList<Child>();
        p = Files.readArrayListFromFile("parents.ser");
        c = Files.readArrayListFromFile("children.ser");
        boolean flag = true;
        
        if(radParent.isSelected()){
            for(Parent pr: p){
                if(pr.getUsername().equals(txtUName.getText())){
                    signSucc.setText("This username had been taken!");
                    flag = false;
                }
            }
            if(flag){
                p.add(new Parent(txtUName.getText(),txtPassword.getText()));
                Files.writeArrayListToFile(p, "parents.ser");
                signSucc.setText("Signed Successfully!");
            }   
            
        }
        
        if(radChild.isSelected()){
            for(Child ch: c){
                if(ch.getUsername().equals(txtUName.getText())){
                    signSucc.setText("This username had been taken!");
                    flag = false;
                }
            }
            if(flag){
                c.add(new Child(txtUName.getText(),txtPassword.getText()));
                Files.writeArrayListToFile(c, "children.ser");
                signSucc.setText("Signed Successfully!");
            }
            
        }
        
        if(!radParent.isSelected() && !radChild.isSelected()){
            signSucc.setText("Please choose Child or Parent!");
        }
        
    }//GEN-LAST:event_btnSignMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnSign;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUName;
    private javax.swing.JRadioButton radChild;
    private javax.swing.JRadioButton radParent;
    private javax.swing.JLabel signSucc;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUName;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
